### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yakko-chn** [yakko-chn/furima-30117#9]
フリマアプリのURL：https://furima-30117.herokuapp.com/
basic認証：user：reset
                   password：yada3zb
出品者/Email：testma5@sample.com
　　　  PW：55curry
購入者/Email：testma55@sample.com
　　　  PW：555curry

よろしくお願いします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
### [修正箇所]
**①ログインしているユーザーだけが、出品ページへ遷移できるようにしましょう！**

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

※今回クレジットカードの情報の記載がなかったため、カリキュラムに記載されているカード情報で確認しています。
※必須項目ではありませんが、購入画面の画像が、購入したい商品のものにならないため、必要があれば修正をお願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回と同様の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①ログインしているユーザーだけが、出品ページへ遷移できるようにしましょう！**
現状、トップページ右下にある、出品するボタンを押すと、出品ページに遷移できてしまいます。

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yakko-chn** [comment]
何度も申し訳ありません。
再度、修正を行いましたのでご確認お願いします。

**Comment by ayanasunakawa** [comment]
富山さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、前回ご依頼させていただいた項目の修正確認はできました。
ただし、追加で以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]
**①ログアウトした状態で、商品詳細ページを閲覧できるように実装しましょう！**
（現在はログインページに遷移します。）

**②購入内容の確認画面で必要情報を全て入力しても購入できない状態です。正常に商品を購入できるようにしましょう！**
※上記理由により、商品購入後の挙動は確認できていないので、次回ご提出時に合わせて確認させていただきます。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yakko-chn** [comment]
ご確認ありがとうございます！
修正を行いましたので、ご確認お願いします。
本番環境で確認したところ、購入できるようなのですが下記の挙動では不備がありますでしょうか？
購入挙動：https://gyazo.com/29c9e6bbb6a00dd1683da85096c0db02

**Comment by ayanasunakawa** [comment]
挙動確認にお時間いただきありがとうございます。ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
